package edu.mum.ui.ccard;

import java.awt.event.ActionEvent;
import java.util.Iterator;
import java.util.List;

import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

import edu.mum.framework.IEntry;

public class JDialog_Transaction extends JDialog {

	private CardFrm parentframe;
	private String accnr;

	private Object rowdata[];
	private DefaultTableModel model;
	private JTable JTable1;
	
	private JLabel JLabel1 = new JLabel();
	private JLabel JLabel2 = new JLabel();
	private JButton JButton_OK = new JButton();
	
	
	public JDialog_Transaction(CardFrm parent, String aaccnr, List<IEntry> entries) {
		super(parent);
		parentframe = parent;
		accnr = aaccnr;
		// This code is automatically generated by Visual Cafe when you add
		// components to the visual environment. It instantiates and initializes
		// the components. To modify the code, only use code syntax that matches
		// what Visual Cafe can generate, or Visual Cafe may be unable to back
		// parse your Java file into its visual environment.
		// {{INIT_CONTROLS
		setTitle("Tansaction Detail");
		setModal(true);
		getContentPane().setLayout(null);
		setSize(268, 126);
		setVisible(false);

		JLabel1.setText("Acc No: ");
		getContentPane().add(JLabel1);
		JLabel1.setForeground(java.awt.Color.black);
		JLabel1.setBounds(22, 12, 80, 24);

		JLabel2.setText(accnr);
		getContentPane().add(JLabel2);
		JLabel2.setForeground(java.awt.Color.black);
		JLabel2.setBounds(104, 12, 148, 24);
		
		JScrollPane JScrollPane1 = new JScrollPane();
		model = new DefaultTableModel();
		JTable1 = new JTable(model);

		model.addColumn("Date");
		model.addColumn("Transaction");
		model.addColumn("Amount");
		rowdata = new Object[3];

		getContentPane().add(JScrollPane1);
		getContentPane().add(JScrollPane1);
		JScrollPane1.setBounds(24, 42, 444, 160);
		JScrollPane1.getViewport().add(JTable1);
		JTable1.setBounds(0, 0, 420, 0);

		// iterator pattern
		Iterator<IEntry> it = entries.iterator();
		while (it.hasNext()) {
			addToTable(it.next());
		}

		// {{REGISTER_LISTENERS
		JButton_OK.addActionListener((event) -> JButtonOK_actionPerformed(event));
		// }}
	}

	void JButtonOK_actionPerformed(ActionEvent event) {
		dispose();
	}

	private void addToTable(IEntry entry) {
		rowdata[0] = entry.getDate();
		rowdata[1] = entry.getDetail();
		rowdata[2] = String.valueOf(entry.getAmount());

		model.addRow(rowdata);
		JTable1.getSelectionModel().setAnchorSelectionIndex(-1);
	}

}